# Labelling & Cleaning

In [1]:
import pandas as pd

# Load raw Strava data
df = pd.read_csv("../data/raw/strava_activities_raw_latest.csv")

print("Total activities:", len(df))
df.head()

Total activities: 280

,Activity ID,Activity Date,Activity Name,Activity Type,Activity Description,Elapsed Time,Distance,Max Heart Rate,Relative Effort,Commute,...,Recovery,With Pet,Competition,Long Run,For a Cause,With Kid,Downhill Distance,Total Sets,Total Reps,Media
0,18078046885,"Apr 12, 2026, 10:17:29 AM",run after the rain,Run,60 min run,3641,6.05,168.0,66.0,NaN,...,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,media/98c0b4ff-2549-45e7-ab4c-abc0c6f82f9a.jpg
1,18076930265,"Apr 10, 2026, 11:54:03 AM",Strength,Weight Training,2026-04-10 18:54:03 HUAWEI Band 10,9245,0,154.0,27.0,NaN,...,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,media/49eb7dcc-7d52-41b9-b4e0-d949ba6c73d0.jpg
2,18045986822,"Apr 9, 2026, 8:58:52 AM",Pool swim,Swim,2026-04-09 15:58:52 HUAWEI Band 10,2067,475,169.0,29.0,NaN,...,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
3,18045986885,"Apr 9, 2026, 8:22:35 AM",Pool swim,Swim,2026-04-09 15:22:35 HUAWEI Band 10,2164,350,166.0,42.0,NaN,...,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
4,18025344730,"Apr 8, 2026, 10:43:14 AM",30 min,Run,11 x 40 sec strides\n1 x 120 sec strides,1803,3.56,173.0,33.0,NaN,...,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN

In [2]:
df.columns

Index(['Activity ID', 'Activity Date', 'Activity Name', 'Activity Type',
       'Activity Description', 'Elapsed Time', 'Distance', 'Max Heart Rate',
       'Relative Effort', 'Commute',
       ...
       'Recovery', 'With Pet', 'Competition', 'Long Run', 'For a Cause',
       'With Kid', 'Downhill Distance', 'Total Sets', 'Total Reps', 'Media'],
      dtype='object', length=103)

In [3]:
# Keep running activities only
runs = df[df["Activity Type"] == "Run"].copy()

print("Total runs:", len(runs))
runs[["Activity Date", "Distance", "Moving Time", "Average Heart Rate"]].head()

Total runs: 145

               Activity Date Distance  Moving Time  Average Heart Rate
0  Apr 12, 2026, 10:17:29 AM     6.05       3068.0               155.0
4   Apr 8, 2026, 10:43:14 AM     3.56       1615.0               155.0
6   Apr 7, 2026, 10:06:27 AM     6.38       3423.0               154.0
8    Apr 5, 2026, 9:36:48 AM     9.98       5235.0               158.0
9    Apr 4, 2026, 9:43:23 AM     9.39       4718.0               161.0

In [4]:
# drop run without HR data 
runs = runs.dropna(subset=["Average Heart Rate"])

# convert date (Strava-safe)
runs["Activity Date"] = pd.to_datetime(
    runs["Activity Date"],
    format="mixed"
)

# sort by date
runs = runs.sort_values(by="Activity Date")

print("Runs with HR data:", len(runs))
runs.head()
runs.to_csv("../data/processed/runs_with_hr.csv", index=False)

Runs with HR data: 121

## Pace calculation

In [5]:
# avg speed is in m/s -> convert to pace in min/km
runs["pace_min_per_km"] = 1000 / (runs["Average Speed"] * 60)
runs[["Average Speed", "pace_min_per_km"]].head()

     Average Speed  pace_min_per_km
251          2.409         6.918500
248          2.364         7.050197
246          2.176         7.659314
244          2.176         7.659314
241          1.819         9.162544

## what will happend 

1. no analysis
2. only labelling
    - 2 type of labelling = 
        - training phase (body condition & program)
        - intensity zone (MAF - Based)

## Traning Phase Labelling

in this part there will be 4 label 

1. pre_injury  (before injury) old baseline before ITBS
2. post_injury  (September 2025 3 times a week run) 
3. return_to_run (October 2025 3 times a week run till the end of the 2025)
4. building_intensity (MAF block progressve)

prety much like that.. hopefully i know what i'm doing

In [6]:
runs["training_phase"] = "building_intensity"

In [7]:
# pre-injury
runs.loc[
    runs["Activity Date"] < "2025-09-01",
    "training_phase"
] = "pre_injury"

# post injury
runs.loc[
    (runs["Activity Date"] >= "2025-09-01") &
    (runs["Activity Date"] < "2025-10-01"),
    "training_phase"
] = "post_injury"

# return_to_run
runs.loc[
    (runs["Activity Date"] >= "2025-10-01") &
    (runs["Activity Date"] < "2025-11-01"),
    "training_phase"
] = "return_to_run"

## Intensity Zone (MAF BASED) Labeling

zone definition = 

1. maf_pure ->           avg hr <= 154 
2. maf_tolerated ->      154 < avg hr <= 164
3. non_maf ->            avg hr > 164   
4. no_hr ->              HR data empty (NA)

In [8]:
MAF_HR = 154
MAF_TOLERANCE = 10


runs["maf_zone"] = "no_hr"

In [9]:
runs["maf_zone"] = "non_maf"

runs.loc[
    runs["Average Heart Rate"] <= MAF_HR,
    'maf_zone'
] = "maf_pure"

runs.loc[
    (runs["Average Heart Rate"] > MAF_HR) &
    (runs["Average Heart Rate"] <= MAF_HR + MAF_TOLERANCE),
    "maf_zone"
] = "maf_tolerated"

In [10]:
runs.groupby(["training_phase", "maf_zone"]).size()

training_phase      maf_zone
building_intensity  maf_pure         43
                    maf_tolerated    26
post_injury         maf_tolerated     1
                    non_maf           1
pre_injury          maf_pure          7
                    maf_tolerated    18
                    non_maf          16
return_to_run       maf_pure          9
dtype: int64

## Training Complience Check

In [11]:
building = runs.loc[
    runs["training_phase"] == "building_intensity"
].copy()

building["maf_zone"].value_counts(normalize=True) * 100

maf_zone
maf_pure         62.318841
maf_tolerated    37.681159
Name: proportion, dtype: float64

In [12]:
tolerated_ratio = (
    building["maf_zone"]
    .value_counts(normalize=True)
    .get("maf_tolerated", 0)
)

if tolerated_ratio > 0.4:
    print("🚨 WARNING: MAF tolerated > 40% — hold volume & slow down")
elif tolerated_ratio > 0.3:
    print("⚠️ CAUTION: MAF tolerated > 30% — monitor closely")
else:
    print("✅ MAF compliance OK")

⚠️ CAUTION: MAF tolerated > 30% — monitor closely

well, according to that i kinda in the yellow zone, i need to keep it easy for a while, and monitor it closely. to anyone dont get injured.

In [13]:
runs.to_csv("../data/processed/runs_labeled.csv", index=False)

so after the first performance analysis i can see that i have an ideal avg heart rate to use insteadof the maf heartrate or the maf zones

and cause of that im gonna make a new labeling for the heartrate zone for maf. it will be like the code below that im about to type.

In [14]:
runs["maf_band"] = "no_hr"

runs.loc[
    runs["Average Heart Rate"] <= 155,
    "maf_band"
] = "maf_clean"

runs.loc[
    (runs["Average Heart Rate"] > 155) &
    (runs["Average Heart Rate"] <= 160),
    "maf_band"
] = "maf_tolerated"

runs.loc[
    runs["Average Heart Rate"] > 160,
    "maf_band"
] = "non_maf"

its basiclly almost the same or just the same but the bpm is just different. its because according to the performance analysis i have an ideal bpm which is 155-160 bpm because there is so many runs in that area of bpm that just make me able to run faster and improve my aerobic capacity. for the simple thing is at the avg heartrate of <= 155 or 155 to 160 bpm i have a good running performance and actually improve my aerobic capacity to a higher level. hopefully you understand what i mean

In [15]:
runs.groupby(["training_phase", "maf_zone"]).size()

training_phase      maf_zone
building_intensity  maf_pure         43
                    maf_tolerated    26
post_injury         maf_tolerated     1
                    non_maf           1
pre_injury          maf_pure          7
                    maf_tolerated    18
                    non_maf          16
return_to_run       maf_pure          9
dtype: int64

In [16]:
runs.to_csv("../data/processed/runs_labeledv2.csv", index=False)